### ISSUE TITLE
Have Endless Key flavor metainfo.xml

### ISSUE THREAD

**Issue by starnight** [endlessm/endless-key-flatpak#15]
Flatpak on [Flathub](https://flathub.org/) should provide `metainfo.xml`.  Here is [the page of Kolibri](https://flathub.org/apps/org.learningequality.Kolibri) on Flathub. It is described by  [data/metainfo/org.learningequality.Kolibri.metainfo.xml.in.in](https://github.com/learningequality/kolibri-installer-gnome/blob/master/data/metainfo/org.learningequality.Kolibri.metainfo.xml.in.in).

So, Endless Key (Linux) should modified the [metainfo.xml](https://github.com/endlessm/endless-key-flatpak/blob/main/data/metainfo/org.learningequality.Kolibri.metainfo.xml.in.in) with Endless Key flavor, too.

**Comment by starnight** [comment]
Do we need URLs: **donation**, **help** and **translate** in the metainfo.xml?

**Comment by pwithnall** [comment]
> Do we need URLs: **donation**, **help** and **translate** in the metainfo.xml?

It probably can’t hurt. It could be a bit confusing to point users to Learning Equality web pages for an Endless product, but if it results in donations to LE or new translations then that’s a good thing for everyone.

**Comment by dbnicholson** [comment]
Since this is the listing that shows up in App Center and Flathub, ultimately we're going to need some design oversight so it's polished like the Google Play page. So, just do your best for now as this will definitely get tweaked later.

**Comment by starnight** [comment]
The desktop entry is "Endless Key" now.
![Screenshot from 2023-09-01 17-18-56](https://github.com/endlessm/endless-key-flatpak/assets/2100946/a0dc90ca-2a20-4c1f-8095-7db7cba191fc)
Here is the picture showing the metainfo
![Screenshot from 2023-09-01 17-15-21](https://github.com/endlessm/endless-key-flatpak/assets/2100946/20fcb9ba-5716-4492-bce5-0e6aee6f32d2)
