### ISSUE TITLE
Adapt the store listings metainfo for the Endless Key flatpak

### ISSUE THREAD

**Issue by jofilizola** [endlessm/endless-key-flatpak#20]
We need to adapt the metainfo we already have in place for Google Play and for Microsoft Store to Flathub.

**Comment by dbnicholson** [comment]
@jofilizola I'm happy to help land the changes here if you can provide guidance. The current listing is defined [here](https://github.com/endlessm/endless-key-flatpak/blob/main/data/metainfo/org.endlessos.Key.metainfo.xml.in.in). We'll also need some screenshots, but the app needs a bit more work to make that happen.

You may already be familiar with this and it's probably too technical, but [this](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-filespec) is the specification for what can be put in there. I think we'd want guidance at least on the following:

* [summary](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-summary)
* [icon](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon)
* [description](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description)
* [keywords](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-keywords)
* [url](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url)
* [content_rating](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-content_rating)
* [branding](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding)

**Comment by jofilizola** [comment]
Thanks Dan!
I assigned this to Cassidy because he volunteered to help :orange_heart: He controls with the GooglePlay listing already, and what needs to be adapted.
But looking to the list you just shared I probably need to provide the assets and some more info.

**Icon**
[Here](https://www.dropbox.com/scl/fo/mjg742isqo8cigmxpmvwn/h?rlkey=r7r6ylrszimroens5bokgqpje&dl=0) I have the icons is several formats as required by Google and Microsoft. 
I should probably export an SVG version, right? That should have the rounded corners (the other platforms require square corners as they have different masks applied)
I suppose using these [guidelines](https://developer.gnome.org/hig/guideline) and this [template](https://gitlab.gnome.org/Teams/Design/HIG-app-icons/blob/master/template.svg) will be the right thing to do?

**Screenshots**
https://www.dropbox.com/scl/fo/8o6g313rta63vq0vs9eva/h?rlkey=4ll58noe1atlc5wu28u5qn67z&dl=0

**Comment by starnight** [comment]
According to the [icon list](https://github.com/endlessm/endless-key-flatpak/tree/main/data/icons), the sizes are
- 64x64
- 128x128
- 256x256
- 512x512

**Comment by cassidyjames** [comment]
@starnight we can just provide a 512×512 icon (or better: a vector) and then I can downscale to the others—we don't hint them to specific sizes, so that's fine.

**Comment by jofilizola** [comment]
I've added the SVG (EK Flathub Launcher 512×512) to the same folder: https://www.dropbox.com/scl/fo/mjg742isqo8cigmxpmvwn/h?rlkey=r7r6ylrszimroens5bokgqpje&dl=0
