### ISSUE TITLE
"Show me" button does not respond

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/endless-key-flatpak#40]
Test package: https://github.com/endlessm/endless-key-flatpak/actions/runs/6153210584

After the test Explorer Start pack completes downloading, click on the "show me" button does not have any responses.

[kolibri.txt](https://github.com/endlessm/endless-key-flatpak/files/12584372/kolibri.txt)

-----

- [x] https://github.com/endlessm/kolibri-explore-plugin/issues/804

**Comment by dylanmccall** [comment]
- https://github.com/endlessm/kolibri-explore-plugin/issues/804

**Comment by dylanmccall** [comment]
Thanks for noticing this! I proposed a fix in https://github.com/endlessm/kolibri-explore-plugin/pull/805.

**Comment by dbnicholson** [comment]
This is released in kolibri-explore-plugin 6.47.0. I'm moving this issue back to In Progress since the flatpak will have to be updated to use the new version. @starnight can you take a look at that?

**Comment by vanessa-chang** [comment]
Verified Passed in 6.47.0 flatpack version
