### ISSUE TITLE
Publish the Endless Key app on Flathub

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/endless-key-flatpak#5]
We want to avoid Endless users installing the Endless Key app until after our OS image has been updated to include the Endless Key version of eos-kolibri-system-helper.

**Comment by starnight** [comment]
[App Submission](https://github.com/flathub/flathub/wiki/App-Submission) shows how to submit a new application to Flathub.

**Comment by starnight** [comment]
GNOME 44 flatpak runtime's Python is version 3.10:
```
$ flatpak run --command=python org.gnome.Platform//44 --version
Python 3.10.12
```

**Comment by starnight** [comment]
Another question: Which open source License should we use for this project?
Still the [MIT](https://github.com/flathub/org.learningequality.Kolibri/blob/master/LICENSE) like [org.learningequality.Kolibri](https://github.com/flathub/org.learningequality.Kolibri)?  Or, others?

**Comment by starnight** [comment]
I think this is blocked on [Create a flatpak manifest for an Endless Key app](https://github.com/endlessm/endless-key-flatpak/issues/4)

**Comment by starnight** [comment]
The working is at https://github.com/starnight/flathub/tree/org.endlessos.Key
Have some temporary files first.

**Comment by starnight** [comment]
The draft is at https://github.com/starnight/flathub/tree/org.endlessos.Key

**Comment by starnight** [comment]
According to Flathub's [Requirements](https://docs.flathub.org/docs/for-app-authors/requirements/#stable-releases-reproducible-builds), it only accepts stable application releases.  So, I release endless-key-flatpak as the tag [`endlesskey_1.0.0`](https://github.com/endlessm/endless-key-flatpak/releases/tag/endlesskey_1.0.0).

Because, endless-key-flatpak might do rebase action based on upstream [kolibri-installer-gnome](https://github.com/learningequality/kolibri-installer-gnome) in the future.  I add the tag with prefix `endlesskey_`.

Use the number **1.0.0** as the publish baseline now.  We can sync up the version of [kolibri-explore-plugin](https://github.com/endlessm/kolibri-explore-plugin) after we include kolibri-explore-plugin, like [endless-key-app](https://github.com/endlessm/endless-key-app) and [kolibri-installer-android](https://github.com/endlessm/kolibri-installer-android).

**Comment by dbnicholson** [comment]
Before we get too far, can we roll the version back to 0.1? I would not call the current version 1.0.0 because it support the explore plugin yet.

**Comment by dbnicholson** [comment]
I created #24 to set the version back to `0.1` and hope we can use the simpler `vX.Y` as the tag. I think the `endlesskey_` in the tag names is superfluous.

**Comment by dbnicholson** [comment]
> According to Flathub's [Requirements](https://docs.flathub.org/docs/for-app-authors/requirements/#stable-releases-reproducible-builds), it only accepts stable application releases. So, I release endless-key-flatpak as the tag [`endlesskey_1.0.0`](https://github.com/endlessm/endless-key-flatpak/releases/tag/endlesskey_1.0.0).
> 
> Because, endless-key-flatpak might do rebase action based on upstream [kolibri-installer-gnome](https://github.com/learningequality/kolibri-installer-gnome) in the future. I add the tag with prefix `endlesskey_`.
> 
> Use the number **1.0.0** as the publish baseline now. We can sync up the version of [kolibri-explore-plugin](https://github.com/endlessm/kolibri-explore-plugin) after we include kolibri-explore-plugin, like [endless-key-app](https://github.com/endlessm/endless-key-app) and [kolibri-installer-android](https://github.com/endlessm/kolibri-installer-android).

I think it's very unlikely we'll do any more rebases from kolibri-installer-gnome as we further diverge. Possibly there can be some cherry picks in either direction, but the last rebase was already pretty messy and duplicated commits that originated here.

Changing the version number is to me a pretty clear indication that this is a separate application with its own development. The more likely approach is that the common work goes into a Kolibri base app (#2) and then there's definitely no reason for further shared development history between the apps.

**Comment by dbnicholson** [comment]
#24 was merged, so I created a [v0.1 tag](https://github.com/endlessm/endless-key-flatpak/releases/tag/v0.1) and added a suggestion on the flathub PR to adjust accordingly.

**Comment by dbnicholson** [comment]
Yes, but I'm hoping to get a little parallel path effort here. What I don't want is to have the Endless Key experience all polished up and ready to be used and then we can't actually install it anywhere because we're waiting for it to be processed by Flathub.

I'd personally rather get the Flathub setup ready while we iterate. To me, exists on Flathub != launch the app. Which is also why I rolled the version back to 0.1. However, you likely have more experience here. If you think it's better to not have it exist on Flathub until we're ready for the world to see it and you feel like we can get the submission process done in a timely manner, then I don't mind waiting.

**Comment by starnight** [comment]
The new test version is built by Flathub https://github.com/flathub/flathub/pull/4481#issuecomment-1718706603

**Comment by dbnicholson** [comment]
We're live!

https://github.com/flathub/org.endlessos.Key

If I understand [this comment](https://github.com/flathub/flathub/pull/4481#issuecomment-1721880575) correctly, @starnight will be invited to collaborate. I think we actually want Endless organization collaboration, which we've done for other apps. I don't remember how that's done, though. @cassidyjames @GeorgesStavracas ?

**Comment by dbnicholson** [comment]
Per Bart on flathub matrix:

> merged and added flathub/endless to collaborators

So, I guess however is in the `flathub/endless` team. I'm not sure who that is, though.

**Comment by cassidyjames** [comment]
@dbnicholson I think Rob, Will, and I are in that team at least, but yeah we should request @endlessm/app I think

**Comment by cassidyjames** [comment]
It's now live and verified. https://flathub.org/apps/org.endlessos.Key

**Comment by dbnicholson** [comment]
> @dbnicholson I think Rob, Will, and I are in that team at least, but yeah we should request @endlessm or @endlessm/endless-developers I think

It appears I'm in it since I was automatically subscribed and can do some privileged things. I think Will got most if not all of the engineers added.

**Comment by vanessa-chang** [comment]
Verified passed as it's available in the stable branch

**Comment by wjt** [comment]
@dbnicholson you and I are labelled as "maintainers" of the https://github.com/orgs/flathub/teams/endless/members team. I have just removed Philip from that group :(

I'm not sure to whom the group is visible. The remaining members as of now are (in no particular order, thanks GitHub):

dsd
manuq
wjt
dylanmccall
ramcq
cassidyjames
starnight
dbnicholson
vanessa-chang

I think that's right.
