### ISSUE TITLE
Key on EOS: App center screenshots have wrong order

### ISSUE THREAD

**Issue by erikos** [endlessm/endless-key-flatpak#50]
Now it looks like:
![Screenshot 2023-09-13 at 13 32 30](https://github.com/endlessm/endless-key-flatpak/assets/51095367/4bd4b116-f162-4f10-b7dd-02fdffbfd6da)

The order should be:
![Screenshot 2023-09-13 at 13 30 13](https://github.com/endlessm/endless-key-flatpak/assets/51095367/77cbd156-bfc5-4a40-8fe7-df32cd5afd4f)

**Comment by pwithnall** [comment]
@erikos How are you viewing this in gnome-software? i.e. Which repos do you have enabled that it’s loading from, or are you viewing the local metainfo file manually?

**Comment by erikos** [comment]
> @erikos How are you viewing this in gnome-software? i.e. Which repos do you have enabled that it’s loading from, or are you viewing the local metainfo file manually (or something else)?

Ahh, I installed the Flatpak from the build artifact. Not through Flathub.

**Comment by erikos** [comment]
This is actually how the Flatpak after installation through Flathub looks like for me in "Software".


![Image](https://github.com/endlessm/endless-key-flatpak/assets/3714785/91f6f1bb-f836-467c-ad91-90487ab4f936)

I do not have images at all.

**Comment by cassidyjames** [comment]
afaik you can't determine the exact order, you can just specify which one should be the main one. But in practice I thought Software/App Center just loaded them in the order they're defined.

This might be less relevant once we update with screenshots of the app itself instead of marketing images, though.

**Comment by starnight** [comment]
I get the correct screenshots order with [Metainfo: Add numbers to the screenshot captions](https://github.com/endlessm/endless-key-flatpak/pull/64).
So, I release [v0.4](https://github.com/endlessm/endless-key-flatpak/releases/tag/v0.4)

**Comment by cassidyjames** [comment]
(Re-)Reported upstream to Flathub as well: https://github.com/flathub/website/issues/1995

**Comment by vanessa-chang** [comment]
Verified passed in version 0.5
