### ISSUE TITLE
Key on EOS: biohazard item is irritating

### ISSUE THREAD

**Issue by erikos** [endlessm/endless-key-flatpak#51]
Let’s remove the biohazard icon and say (Beta) or something similar.

![Screenshot from 2023-09-13 15-41-06](https://github.com/endlessm/endless-key-flatpak/assets/3714785/01cebc4a-6776-4356-ac48-2c3c30aa62cf)
![Screenshot from 2023-09-13 15-39-31](https://github.com/endlessm/endless-key-flatpak/assets/3714785/9ee4b632-47c6-45e5-a9d5-755dee2935fa)

**Comment by dylanmccall** [comment]
This is specific to builds of `org.endlessos.Key.Devel`, just following a pattern that is used for many other GNOME apps. Unless #5 gets completely stalled, I don't think in two weeks we'll be installing `.Devel` builds for any case outside of a developer testing a build on their own system. But if that's definitely an issue in the short term, I think changing "☢️" to "(Nightly)" makes fine sense, and I also created https://github.com/endlessm/endless-key-flatpak/pull/53 to make sure we are communicating that it is a development build in all the usual ways.

**Comment by erikos** [comment]
Yes, not visible when installing from Flathub. Thanks for the explanation @dylanmccall
