### ISSUE TITLE
Verify language selection works as expected

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/endless-key-flatpak#56]
We need to verify Endless Key appears in Spanish when it is started on a Spanish Endless OS image, with the system language set to Spanish, such as https://images-dl.endlessm.com/torrents/public/eos-amd64-amd64-es-5.0.5-iso.torrent.

In addition, we should test what happens if Endless Key is started in a separate user account with its own language configured in GNOME Settings.

Note: there are not many Spanish language strings at the moment - we will likely need to do some sleuthing to determine the app is making an effort to appear in Spanish.

- [x] https://github.com/endlessm/endless-key-flatpak/issues/57

**Comment by dylanmccall** [comment]
I was worried there would be other things, but this all seems fine now from my own testing :)

**Comment by dbnicholson** [comment]
Separate user with its own language settings works? Even with the system helper? I didn't look at how the code works, but I was a bit worried that if it's resolved in the system helper it will always get the system language.
