### ISSUE TITLE
Flatpak Localization

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/endless-key-flatpak#6]
Right now we need translation to Spanish. kolibri-installer-gnome already has translation infrastructure in place and all of the code has Spanish translations. However, the desktop and metainfo files aren't translated, and we likely want to change those strings, anyways.

**Comment by jofilizola** [comment]
Needs copywritting: [Adapt the store listings metainfo for the Endless Key flatpak#20](https://github.com/endlessm/endless-key-flatpak/issues/20)

**Comment by jprvita** [comment]
I started looking into how to make this translatable -- it looks like we have some previous localization efforts that are not being used or just outdated.

**Comment by pwithnall** [comment]
As it’s in the backlog, I’m going to steal this. PR ready (assuming I’ve found the right .desktop and .metainfo files): https://github.com/endlessm/endless-key-flatpak/pull/32

After applying this and running `meson compile -C _build kolibri-gnome-update-po`, the following Spanish `.po` file is generated, ready to be translated: 
[es_ES.po.txt](https://github.com/endlessm/endless-key-flatpak/files/12548472/es_ES.po.txt)
