### ISSUE TITLE
Migrate from welcomeScreen to loadingScreen

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/endless-key-flatpak#68]
https://github.com/endlessm/kolibri-explore-plugin/pull/793 reworked the welcome screen so that it runs entirely out of the plugin and doesn't need to be run as a separate JS interface. This will be be in the [next major release](https://github.com/endlessm/kolibri-explore-plugin/issues/815), so the flatpak needs to be prepared for that.

**Comment by dbnicholson** [comment]
FYI, you can use the following from the RC release I made earlier today:

https://pypi.org/project/kolibri-explore-plugin/7.0.0rc3/
https://github.com/endlessm/kolibri-explore-plugin/releases/download/v7.0.0rc3/apps-bundle.zip
https://github.com/endlessm/kolibri-explore-plugin/releases/download/v7.0.0rc3/loading-screen.zip

**Comment by erikos** [comment]
This works fine from a user flow, tested with plugin 7.1 onwards.
