### ISSUE TITLE
Create an Endless Key version of kolibri-gnome

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/endless-key-flatpak#7]
We should create a new fork of the [Kolibri GNOME app](https://github.com/learningequality/kolibri-installer-gnome). This is distinct from [the other fork we have](https://github.com/endlessm/kolibri-installer-gnome) because we expect to carry a small number of changes on top of upstream.

To start with, it should include the following:

- The [reference flatpak manifest](https://github.com/endlessm/kolibri-installer-gnome/tree/master/build-aux/flatpak) should use app ID `org.endlessos.Key.Devel` instead of `org.learningequality.Kolibri.Devel`.
- The application should refer to itself as "Endless Key" instead of "Kolibri", for example in [the About dialog](https://github.com/learningequality/kolibri-installer-gnome/blob/master/src/kolibri_gnome/application.py#L112-L127).
- Like the [Android Endless Key app](https://github.com/endlessm/kolibri-installer-android) and the [Windows Endless Key app](https://github.com/endlessm/endless-key-app), the application should use the [welcome screen from kolibri-explore-plugin](https://github.com/endlessm/kolibri-explore-plugin/tree/master/packages/welcome-screen) as a loading screen. Note there is an in-progress task to remove the welcome screen functionality from this package so it is _only_ a loading screen: https://github.com/endlessm/kolibri-explore-plugin/issues/748. So there should be no need to implement the welcome screen Javascript API like it is in the Windows and Chrome OS apps.
- The [Kolibri Explore plugin](https://github.com/endlessm/kolibri-explore-plugin) should be a required plugin that is always enabled: https://github.com/learningequality/kolibri-installer-gnome/blob/master/src/kolibri_daemon/kolibri_utils.py#L19-L30. The `kolibri.plugins.learn` plugin should always be disabled. (This is required due to the way the Explore plugin sets itself as the default landing page).

**Comment by dbnicholson** [comment]
My only nitpick is that I think the app ID should be `org.endlessos.Key` to match the Android app. I don't think the "Endless" in the "Endless Key" friendly name needs to be separately reflected in the app ID as it's already implied by `org.endlessos`.

**Comment by dbnicholson** [comment]
I think it's best if we make this dependent on https://github.com/endlessm/endless-key-flatpak/issues/1 and https://github.com/endlessm/kolibri-installer-gnome/pull/10. I.e., let's try to land those changes in vanilla `org.learningequality.Kolibri` before forking https://github.com/learningequality/kolibri-installer-gnome.

**Comment by dylanmccall** [comment]
> My only nitpick is that I think the app ID should be `org.endlessos.Key` to match the Android app. I don't think the "Endless" in the "Endless Key" friendly name needs to be separately reflected in the app ID as it's already implied by `org.endlessos`.

Oops! Indeed it should. I'll tweak the description :)

**Comment by dbnicholson** [comment]
@GeorgesStavracas since you're mostly done with the vanilla Kolibri work and @pwithnall is going to be out tomorrow, I think this would be a good next step.

**Comment by starnight** [comment]
I think the PR [Parameterize DBus' bus name](https://github.com/endlessm/kolibri-desktop-auth-plugin/pull/11) helps this.
