### ISSUE TITLE
Endless Key App menu links and info needs replacement

### ISSUE THREAD

**Issue by jofilizola** [endlessm/endless-key-flatpak#71]
The links on the App Menu currently link to Learning Equality's website, not Endless'.

Documentation > 
links to https://kolibri.readthedocs.io/en/latest/
should link to https://support.endlessos.org/en/endless-key

Community Forum >
links to https://community.learningequality.org/
should link to: we don't have a forum for Endless Key... We should create an "Endless Key" category in https://community.endlessos.com/ and link to that

About > Website >
links to: https://learningequality.org/
Should link to: https://www.endlessos.org/key

Remove from menu:
"Open Kolibri Home" and "Open in external browser"

@cassidyjames @erikos does that sound good?

**Comment by jprvita** [comment]
> The links on the App Menu currently link to Learning Equality's website, not Endless'.
> 
> Documentation > links to https://kolibri.readthedocs.io/en/latest/ should link to https://support.endlessos.org/en/endless-key
> 
> Community Forum > links to https://community.learningequality.org/ should link to: we dont have a forum for ENdless Key... should we link to the Endless OS one? or remove?
> 

We could create a "Endless Key" category in our forum and link to it. As an example, [this is how the "Hack" category looks](https://community.endlessos.com/c/hack). The one thing to keep in mind is how to monitor / reply to any incoming traffic there. Also, this would be somewhat overlapping with the "Feedback" button, so maybe removing would make more sense, IDK. I guess it depends on whether we want to foster a community of users talking among themselves,in public, vs users only being able to reach us directly, in private.

**Comment by cassidyjames** [comment]
I wonder with the in-app links plus the About window supporting much more rich information (and Adwaita recently adding the ability to grab About window information straight from AppStream MetaInfo), could we remove a lot of these from the menu?

We could pursue that upstream and explain that the new About window was explicitly designed to house this kind of information if we wanted. Then it is fewer places to sync information, and fewer places for the user to check as well.

I can throw together a mockup/prototype real quick…

**Comment by manuq** [comment]
@dsd has a good point about removing the "Open Kolibri Home" and "Open in external browser" options from the menu.

**Comment by cassidyjames** [comment]
@jofilizola 

>is the idea to remove those links from the menu and add them to the about window? and the info will come from the same source as the flathub info?

Yep, that would make the most sense to me; this is [implemented in the latest version of the Adwaita About window](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/ctor.AboutWindow.new_from_appdata.html), which we should be able to use after #80

>Localization included?

Good point, I need to double check this. I would be surprised if it wasn't handled but I'm not 100% sure.

>What do we need to do to make that happen?

We'd need Libadwaita 1.4 which is included with GNOME 45. So first we'd want to land #80, then we'd need a PR to update how the About window is constructed; I just did this in my own apps, so I could submit a PR here (but it's straightforward enough; any engineer could). And yeah at the same time we could clean up some other menu entries that aren't really relevant to Key as @manuq and @dsd have pointed out.

>Upstream meaning Kolibri?

Yep, it could make sense to move some of this into the About window in Kolibri itself.

**Comment by jofilizola** [comment]
This all sounds good to me! 
I (think) have updated the links here: https://github.com/endlessm/endless-key-flatpak/blob/main/data/metainfo/org.endlessos.Key.metainfo.xml.in.in

So, actions here with be:

- [ ] Clean up menu items
- [ ] Wait for https://github.com/endlessm/endless-key-flatpak/pull/80 to be done, then:
   - [ ] PR to update how the About window is constructed (using Libadwaita 1.4)
   - [ ] Propose the same About page changes to Kolibri (which would be optional?)
