### ISSUE TITLE
Release 0.6

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/endless-key-flatpak#82]
Now that kolibri-explore-plugin 7.0.0 is released, we should make a new 0.6 release that can be consumed in the flathub build. This depends on #81.

**Comment by starnight** [comment]
It has been released as tag [`v0.6`](https://github.com/endlessm/endless-key-flatpak/releases/tag/v0.6).
And, PR [Bump endless key flatpak v0.6](https://github.com/flathub/org.endlessos.Key/pull/3) on Flathub is ready for review.

**Comment by cassidyjames** [comment]
@dbnicholson yep, GNOME 45 release and everyone updating all their Flathub apps has killed the bot 😅
